### ISSUE TITLE
Allow customization of table elements

### ISSUE THREAD

**Issue by NicoAiko** [NicoAiko/zerotwo#65]
# FEATURE REQUEST

Currently the table shows the status as a colored square, the name, the progress, the given score, the season it's aired/airing in and when it was updated the last time.

## Task

- [x] Make the contents variable to some extend (Disallow removal of name and progress!)
- [ ] There should be a place in the settings for it
- [ ] Let the setting be made different for each, AniList and MyAnimeList.
- [ ] Allow customisation for each list status in AniList and MyAnimeList

**Comment by NicoAiko** [comment]
Actually not that interesting anymore, as the table view will change into a card view.

Closing.
